# Generated by Django 5.1.4 on 2024-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_year', models.IntegerField()),
                ('admission_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('first_year_left', models.CharField(blank=True, max_length=20, null=True)),
                ('special_adid', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'admission_details',
                'unique_together': {('sname', 'admission_year')},
            },
        ),
    ]
